In [77]:
import numpy as np

# Writing a neural network in python

Firstly, a neural network is defined by the number of layers, and the number of neurons in each layer.

Let us use a list to denote this.

## Defining layer sizes

In [78]:
# Defining the sizes of the layers in our neural network
layers = [2, 2, 1]

The above code denotes the 3-neuron neural network we saw previously: 2-dimensional input, 2 neurons in a hidden layer, 1 neuron in the output layer.

Generally speaking, a neural network than has more than 1 hidden layer is a **deep** neural network.

## Defining weight matrices

Using the sizes of the layers in our neural network, let us initialize the weight matrices to random values (sampled from a standard normal gaussian, because we know that we need both positive and negative weights).

In [79]:
# Initializing weight matrices from layer sizes
def initializeWeights(layers):
    weights=[np.random.randn(i+1,o) for i,o in zip(layers[:-1],layers[1:])]
    return weights

In [80]:
# Displaying weight matrices
layers = [2, 2, 1]
weights = initializeWeights(layers)

for i in range(len(weights)):
    print(i+1)
    print(weights[i].shape)
    print(weights[i])

1
(3, 2)
[[-0.43778315  2.171257  ]
 [ 1.15231025 -1.81881234]
 [-0.13804934  0.53983961]]
2
(3, 1)
[[-1.77528229]
 [ 1.31487654]
 [-0.47344805]]


# Forward Propagation

The output of the neural network is calculated by **propagating forward** the outputs of each layer.

Let us define our input as an np.array, since we want to represent matrices.

In [81]:
# We shall use np.array() to represent matrices
X = np.array([[0,0], [0,1], [1,0], [1,1]])

## Adding bias terms

Since the input to every layer needs a bias term (1) added to it, let us define a function to do that.

In [82]:
# Add a bias term to every data point in the input
def addBiasTerms(X):
    X=np.array(X)
    X=np.c_[np.ones(X.shape[0]),X]
        
    return X

Use the following cell to test the addBiasTerms function:

In [83]:
# TESTING addBiasTerms

# We shall use np.array() to represent matrices
X = np.array([[0,0], [0,1], [1,0], [1,1]])
print("Before adding bias terms: "); print(X)
X = addBiasTerms(X)
print("After adding bias terms: "); print(X)

Before adding bias terms: 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
After adding bias terms: 
[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]


## Sigmoid function

Let us also define a function to calculate the sigmoid of any np.array given to it:

In [84]:
# Sigmoid function
def sigmoid(a):
    return 1/(1 + np.exp(-a))

## Forward propagation of inputs

Let us store the outputs of the layers in a list called "outputs". We shall use that the output of one layer as the input to the next layer.

In [85]:
# Forward Propagation of outputs
def forwardProp(X, weights):
    # Initializing an empty list of outputs
    outputs = []
    
    # Assigning a name to reuse as inputs
    inputs = X
    
    # For each layer
    for w in weights:
        # Add bias term to input
        inputs = addBiasTerms(inputs)
        
        # Y = Sigmoid ( X .* W^T )
        print(inputs,w)
        outputs.append(sigmoid(np.dot(inputs, w)))
        
        # Input of next layer is output of this layer
        inputs = outputs[-1]
        
    return outputs

In [86]:
# VIEWING FORWARD PROPAGATION
# Set random seeds
np.random.seed(17)

# Initialize network
layers = [2, 3, 3, 1]
#weights = initializeWeights(layers)

# 3-neuron network
weights = initializeWeights(layers)

print("weights:")
for i in range(len(weights)):
    print(i+1); print(weights[i].shape); print(weights[i])

# Input
X = [[0,0], [0,1], [1,0], [1,1]]

print("X:"); print(X)

# Forward propagate X, and save outputs
outputs = forwardProp(X, weights)

print("outputs:")
for o in range(len(outputs)):
    print(o+1); print(outputs[o].shape); print(outputs[o])

weights:
1
(3, 3)
[[ 0.27626589 -1.85462808  0.62390111]
 [ 1.14531129  1.03719047  1.88663893]
 [-0.11169829 -0.36210134  0.14867505]]
2
(4, 3)
[[-0.43778315  2.171257    1.15231025]
 [-1.81881234 -0.13804934  0.53983961]
 [-1.77528229  1.31487654 -0.47344805]
 [-1.0922299  -0.25002744 -0.9822943 ]]
3
(4, 1)
[[ 1.03126909]
 [ 0.49133378]
 [-0.4466466 ]
 [-0.80636008]]
X:
[[0, 0], [0, 1], [1, 0], [1, 1]]
[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]] [[ 0.27626589 -1.85462808  0.62390111]
 [ 1.14531129  1.03719047  1.88663893]
 [-0.11169829 -0.36210134  0.14867505]]
[[1.         0.56863052 0.13533042 0.65110527]
 [1.         0.5410493  0.09825821 0.6840779 ]
 [1.         0.80558555 0.30630785 0.92487742]
 [1.         0.78749289 0.2351351  0.93457669]] [[-0.43778315  2.171257    1.15231025]
 [-1.81881234 -0.13804934  0.53983961]
 [-1.77528229  1.31487654 -0.47344805]
 [-1.0922299  -0.25002744 -0.9822943 ]]
[[1.         0.08140402 0.89166928 0.68040434]
 [1.         0.08758728 0.886424