<a href="https://colab.research.google.com/github/chenguanhua/test/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.5901 - accuracy: 0.7193
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4810 - accuracy: 0.8011
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4507 - accuracy: 0.8023
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4348 - accuracy: 0.8050
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.8079
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4149 - accuracy: 0.8077
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4062 - accuracy: 0.8100
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3969 - accuracy: 0.8164
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3870 - accuracy: 0.8341
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3760 - accuracy: 0.8424

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 192  213]]


0.864

In [ ]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [ ]:
from sklearn.neural_network import MLPClassifier

model=MLPClassifier((6,6))
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(6, 6))

In [ ]:
y_pred=model.predict(X_test)
np.mean(y_pred==y_test)

0.8615

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 197  208]]


0.8615

No gender and geo info

In [ ]:
df=dataset.iloc[:,6:-1]
df['CreditScore']=dataset['CreditScore']
df

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      42       2       0.00              1          1               1   
1      41       1   83807.86              1          0               1   
2      42       8  159660.80              3          1               0   
3      39       1       0.00              2          0               0   
4      43       2  125510.82              1          1               1   
...   ...     ...        ...            ...        ...             ...   
9995   39       5       0.00              2          1               0   
9996   35      10   57369.61              1          1               1   
9997   36       7       0.00              1          0               1   
9998   42       3   75075.31              2          1               0   
9999   28       4  130142.79              1          1               0   

      EstimatedSalary  CreditScore  
0           101348.88          619  
1           112542.58          608  
2           113931.57          502  
3            93826.63          699  
4            79084.10          850  
...               ...          ...  
9995         96270.64          771  
9996        101699.77          516  
9997         42085.58          709  
9998         92888.52          772  
9999         38190.78          792  

[10000 rows x 8 columns]

In [ ]:
X=df.values
y=dataset.iloc[:,-1].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
mean=np.mean(X_train,axis=0)
std=np.std(X_train,axis=0)

X_train=(X_train-mean)/std
X_test=(X_test-mean)/std

In [ ]:
model=MLPClassifier((6,6))
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(100, 50))

In [ ]:
y_pred=model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1423  172]
 [ 173  232]]


0.8275

add gender

In [ ]:
df=dataset.iloc[:,5:-1]
df['CreditScore']=dataset['CreditScore']
df['Gender']=df['Gender'].apply(lambda row: 0 if row=='Female' else 1)
X=df.values
y=dataset.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
mean=np.mean(X_train,axis=0)
std=np.std(X_train,axis=0)

X_train=(X_train-mean)/std
X_test=(X_test-mean)/std
model=MLPClassifier((6,6))
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1526   69]
 [ 206  199]]


0.8625

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
250/250 [==============================] - 5s 1ms/step - loss: 0.5783 - accuracy: 0.7730
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.5083 - accuracy: 0.7959
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4761 - accuracy: 0.7965
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4573 - accuracy: 0.7970
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4472 - accuracy: 0.7966
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4407 - accuracy: 0.7986
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4367 - accuracy: 0.8026
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4331 - accuracy: 0.8079
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.8119
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4270 - accuracy: 0.8175

add location

In [ ]:
import numpy as np

loc=np.zeros((len(df),3))

In [ ]:
df=dataset.iloc[:,3:-1]
df['Gender']=df['Gender'].apply(lambda row: 0 if row=='Female' else 1)

for i,country in enumerate(df['Geography']):
  if country=='France':
    loc[i,0]=1
  elif country=='Germany':
    loc[i,1]=1
  else:
    loc[i,2]=1

df[['France','Germany','Spain']]=loc
df.drop('Geography',axis=1,inplace=True)
df

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germany  Spain  
0                  1        101348.88     1.0      0.0    0.0  
1                  1        112542.58     0.0      0.0    1.0  
2                  0        113931.57     1.0      0.0    0.0  
3                  0         93826.63     1.0      0.0    0.0  
4                  1         79084.10     0.0      0.0    1.0  
...              ...              ...     ...      ...    ...  
9995               0         96270.64     1.0      0.0    0.0  
9996               1        101699.77     1.0      0.0    0.0  
9997               1         42085.58     1.0      0.0    0.0  
9998               0         92888.52     0.0      1.0    0.0  
9999               0         38190.78     1.0      0.0    0.0  

[10000 rows x 12 columns]

In [ ]:
X=df.values
y=dataset.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
mean=np.mean(X_train,axis=0)
std=np.std(X_train,axis=0)

X_train=(X_train-mean)/std
X_test=(X_test-mean)/std
model=MLPClassifier((6,6))
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1522   73]
 [ 190  215]]


0.8685

In [ ]:
X[0]

array([6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.0134888e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00])